Repository AY2122S2-CS2113-F10-2/tp, pull requests merged in 2022-03, with the labels that each got.

#21 Add Storage Class
  src/main/java/seedu/duke/InvMgr.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/HiCommand.java
  src/main/java/seedu/duke/exceptions/InvMgrException.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/storage/StorageTest.java
  test/data/load/empty.json
  test/data/load/invalidData.json
  test/data/load/validInputData.json
  test/data/read/actualData.json
  test/data/read/expectedData.json
Labels: type.Story, priority.High

#47 Branch storage cleanup
  src/main/java/seedu/duke/InvMgr.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/data/ItemList.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: priority.High, review.Ready

#48 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: priority.Low, review.Ready

#51 Update DeveloperGuide
  data/inventoryData.json
  docs/DeveloperGuide.md
  docs/diagrams/CommandSequenceDiagram.puml
  docs/img/CommandSequenceDiagram.png
  src/main/java/META-INF/MANIFEST.MF
Labels: type.Task

#53 Branch dev guide
  docs/diagrams/CommandSequenceDiagram.png
  docs/diagrams/StorageClassDiagram.png
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageInitialisationSequenceDiagram.png
  docs/diagrams/StorageInitialisationSequenceDiagram.puml
  docs/diagrams/StorageLoadSequenceDiagram.png
  docs/diagrams/StorageLoadSequenceDiagram.puml
  docs/diagrams/StorageSaveSequenceDiagram.png
  docs/diagrams/StorageSaveSequenceDiagram.puml
  src/main/java/seedu/duke/InvMgr.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Task, priority.High

#54 Add AddCommandSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/img/AddCommandSequenceDiagram.png
Labels: type.Task, priority.High, review.Ready

#55 Add DeleteCommandSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/img/DeleteCommandSequenceDiagram.png
Labels: type.Task, priority.High, review.Ready

#57 Update DeveloperGuide [Command and DescCommand]
  docs/DeveloperGuide.md
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/CommandSequenceDiagram.puml
  docs/diagrams/DescCommandSequenceDiagram.puml
  docs/img/CommandClassDiagram.png
  docs/img/CommandSequenceDiagram.png
  docs/img/DescCommandSequenceDiagram.png
Labels: type.Task, review.Ready

#60 Add Parser Component and ListCommand to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/ParserClassDiagram.puml
  docs/img/ListCommandSequenceDiagram.png
  docs/img/ParserClassDiagram.png
Labels: type.Task, priority.High

#59 More Developer Guide updates
  docs/DeveloperGuide.md
  docs/diagrams/CommandSequenceDiagram.png
  docs/diagrams/StorageClassDiagram.png
  docs/diagrams/StorageLoadSequenceDiagram.png
  docs/diagrams/StorageSaveSequenceDiagram.png
  docs/diagrams/StorageSaveSequenceDiagram.puml
  docs/img/StorageClassDiagram.png
  docs/img/StorageInitialisationSequenceDiagram.png
  docs/img/StorageLoadSequenceDiagram.png
  docs/img/StorageSaveSequenceDiagram.png
Labels: type.Task, priority.High

#62 Add Storage relevant documentation for design & overall app sequence
  docs/DeveloperGuide.md
  docs/diagrams/ApplicationLaunchSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageSaveSequenceDiagram.puml
  docs/img/ApplicationLaunchSequenceDiagram.png
  docs/img/StorageClassDiagram.png
Labels: type.Task, priority.High, review.Ready

#68 Adopt AB3 Parser code into InvMgr
  src/main/java/seedu/duke/InvMgr.java
  src/main/java/seedu/duke/commands/DescCommand.java
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/ArgumentMultimap.java
  src/main/java/seedu/duke/parser/ArgumentTokenizer.java
  src/main/java/seedu/duke/parser/CliSyntax.java
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
  src/main/java/seedu/duke/parser/DescCommandParser.java
  src/main/java/seedu/duke/parser/InputParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
  src/main/java/seedu/duke/parser/Prefix.java
Labels: type.Enhancement, priority.High, review.Ready

#64 Enable assertions on Gradle-built jar
  build.gradle
Labels: type.Task, priority.High, review.Ready

#63 Update docs/DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Low, severity.Low, review.Ready

#72 Add Edit Command
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/data/ItemList.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/CliSyntax.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/InputParser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
Labels: type.Story, priority.High, review.Ready

#70 Update UserGuide v2.0
  docs/UserGuide.md
  test/data/read/actualData.json
Labels: type.Task

#76 Add BorrowCommand, BorrowRecord
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/BorrowCommand.java
  src/main/java/seedu/duke/data/BorrowRecord.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/data/ItemList.java
  src/test/java/seedu/duke/commands/BorrowCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  test/data/read/expectedData.json
  test/data/save/actualData.json
  test/data/save/expectedData.json
Labels: type.Task, priority.High, review.Ready

#75 Implement JUnit test for Parser
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/DescCommand.java
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/commands/SearchCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
  src/main/java/seedu/duke/parser/SearchCommandParser.java
  src/test/java/seedu/duke/parser/AddCommandParserTest.java
  src/test/java/seedu/duke/parser/DeleteCommandParserTest.java
  src/test/java/seedu/duke/parser/DescCommandParserTest.java
  src/test/java/seedu/duke/parser/EditCommandParserTest.java
  src/test/java/seedu/duke/parser/ParserStubs.java
  src/test/java/seedu/duke/parser/ParserUtilsTest.java
  src/test/java/seedu/duke/parser/SearchCommandParserTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  src/test/java/seedu/duke/utils/ParserTestUtils.java
Labels: type.Task, priority.Medium, review.Ready

#88 Change prefixes to match user guide
  src/main/java/seedu/duke/parser/CliSyntax.java
Labels: type.Bug, priority.Medium

#85 Add JUnit tests for SearchCommand
  src/main/java/seedu/duke/commands/SearchCommand.java
  src/test/java/seedu/duke/commands/SearchCommandTest.java
  src/test/java/seedu/duke/parser/AddCommandParserTest.java
  src/test/java/seedu/duke/parser/DeleteCommandParserTest.java
  src/test/java/seedu/duke/parser/DescCommandParserTest.java
  src/test/java/seedu/duke/parser/EditCommandParserTest.java
  src/test/java/seedu/duke/parser/SearchCommandParserTest.java
  src/test/java/seedu/duke/stubs/CommandStubs.java
  src/test/java/seedu/duke/stubs/ItemStubs.java
  src/test/java/seedu/duke/stubs/ParserStubs.java
  src/test/java/seedu/duke/stubs/UiStub.java
Labels: type.Task, priority.Medium

#89 Update test cases to match user guide
  src/test/java/seedu/duke/parser/AddCommandParserTest.java
  src/test/java/seedu/duke/parser/EditCommandParserTest.java
  src/test/java/seedu/duke/parser/SearchCommandParserTest.java
Labels: review.Ready

#90 EditCommand JUnit tests
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/data/ItemList.java
  src/test/java/seedu/duke/commands/EditCommandTest.java
  src/test/java/seedu/duke/commands/SearchCommandTest.java
  src/test/java/seedu/duke/stubs/CommandStubs.java
  src/test/java/seedu/duke/stubs/ItemStubs.java
Labels: type.Task, priority.Medium

#93 Update InputParser Class
  src/main/java/seedu/duke/parser/InputParser.java
Labels: type.Bug, priority.High, severity.High, review.Ready

#95 Update UserGuide to follow DateFormat YYYY-MM-DD
  docs/UserGuide.md
Labels: type.Task, review.Ready

#102 Update BorrowCommand for date input validation
  .gitignore
  data/inventoryData.json
  src/main/java/seedu/duke/commands/BorrowCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/BorrowRecord.java
  src/main/java/seedu/duke/parser/BorrowCommandParser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
  src/test/java/seedu/duke/commands/BorrowCommandTest.java
  src/test/java/seedu/duke/parser/BorrowCommandParserTest.java
  src/test/java/seedu/duke/stubs/ParserStubs.java
Labels: type.Task, review.Ready

#101 Add documentation for Add, Edit, Search, Delete
  docs/UserGuide.md
Labels: type.Task, priority.High, review.Ready

#96 Add ListFutureBorrowingsCommand
  src/main/java/seedu/duke/commands/ListFutureBorrowingsCommand.java
  src/main/java/seedu/duke/parser/InputParser.java
  src/main/java/seedu/duke/parser/ListFutureBorrowingsParser.java
Labels: type.Story, priority.High, review.Ready

#104 Add ListCurrentBorrowingsCommand
  src/main/java/seedu/duke/commands/ListCurrentBorrowingsCommand.java
  src/test/java/seedu/duke/commands/ListCurrentBorrowingsCommandTest.java
  src/test/java/seedu/duke/stubs/CommandStubs.java
Labels: type.Task

#97 Add ListOverdueBorrowingsCommand
  src/main/java/seedu/duke/commands/ListOverdueBorrowingsCommand.java
  src/main/java/seedu/duke/parser/InputParser.java
  src/main/java/seedu/duke/parser/ListOverdueBorrowingsParser.java
Labels: type.Story, priority.High

#105 Add BorrowRecordStubs.java
  src/test/java/seedu/duke/stubs/BorrowRecordStubs.java
Labels: review.Ready

#106 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Low, review.Ready

#94 General bugfix collections
  .gitignore
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/DescCommand.java
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/commands/SearchCommand.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/data/ItemList.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/commands/SearchCommandTest.java
  src/test/java/seedu/duke/stubs/CommandStubs.java
Labels: type.Enhancement, priority.Low, review.Ready

#107 Update Stubs for testing with borrowing records
  src/main/java/seedu/duke/data/ItemList.java
  src/test/java/seedu/duke/commands/ListCurrentBorrowingsCommandTest.java
  src/test/java/seedu/duke/stubs/CommandStubs.java
Labels: type.Enhancement, review.Ready

#113 Add ListCurrentBorrowingsParser
  src/main/java/seedu/duke/parser/InputParser.java
  src/main/java/seedu/duke/parser/ListCurrentBorrowingsParser.java
  src/test/java/seedu/duke/commands/BorrowCommandTest.java
Labels: type.Task, review.Ready

#114 Update UserGuide for BorrowCommand
  docs/UserGuide.md
Labels: type.Enhancement

#118 Update ListCurrentBorrowingsCommand
  src/main/java/seedu/duke/commands/ListCurrentBorrowingsCommand.java
Labels: type.Enhancement

#117 Update DeveloperGuide
  docs/DeveloperGuide.md
Labels: type.Task, review.Ready
