Repository AY2122S2-CS2113-F10-2/tp, pull requests merged in 2022-04, with the labels that each got.

#125 Add CancelFutureBorrowings
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/CancelFutureBorrowingsCommand.java
  src/main/java/seedu/duke/commands/ListAvailableBorrowingsCommand.java
  src/main/java/seedu/duke/commands/ListFutureBorrowingsCommand.java
  src/main/java/seedu/duke/parser/CancelFutureBorrowingsParser.java
  src/main/java/seedu/duke/parser/InputParser.java
  src/main/java/seedu/duke/parser/ListAvailableBorrowingsParser.java
Labels: type.Story, priority.Medium

#165 Created PPP template. Add lestersimjj PPP.
  docs/team/johndoe.md
  docs/team/lestersimjj.md
  docs/team/template.md
Labels: type.Task

#163 Update BorrowCommand and BorrowCommandParser
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/BorrowCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/BorrowRecord.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/data/ItemList.java
  src/main/java/seedu/duke/parser/BorrowCommandParser.java
  src/test/java/seedu/duke/commands/BorrowCommandTest.java
  src/test/java/seedu/duke/data/BorrowRecordTest.java
  src/test/java/seedu/duke/parser/BorrowCommandParserTest.java
  src/test/java/seedu/duke/stubs/CommandStubs.java
Labels: type.Bug, severity.Medium

#175 Add PPP quitejasper.md
  docs/team/quitejasper.md
Labels: type.Task, priority.Medium, review.Ready

#169 PPP Draft
  docs/team/IncompetentDev.md
Labels: type.Task, review.Ready

#179 Update ListCurrentBorrowingsCommand with Java Streams
  src/main/java/seedu/duke/commands/BorrowCommand.java
  src/main/java/seedu/duke/commands/ListCurrentBorrowingsCommand.java
  src/main/java/seedu/duke/data/BorrowRecord.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/data/ItemList.java
  src/test/java/seedu/duke/commands/ListCurrentBorrowingsCommandTest.java
  src/test/java/seedu/duke/data/BorrowRecordTest.java
  src/test/java/seedu/duke/data/ItemTest.java
Labels: type.Enhancement, review.Ready

#181 Update BorrowRecord and BorrowCommand
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/BorrowCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/BorrowRecord.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/parser/BorrowCommandParser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
  src/test/java/seedu/duke/commands/BorrowCommandTest.java
  src/test/java/seedu/duke/data/BorrowRecordTest.java
  src/test/java/seedu/duke/parser/BorrowCommandParserTest.java
  src/test/java/seedu/duke/stubs/BorrowRecordStubs.java
  src/test/java/seedu/duke/stubs/ParserStubs.java
Labels: type.Enhancement, type.Task, priority.Medium, review.Ready

#167 PE-D bugfixes
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/commands/SearchCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/BorrowRecord.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
  src/main/java/seedu/duke/parser/SearchCommandParser.java
  src/main/java/seedu/duke/storage/BorrowRecordAdapter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/commands/EditCommandTest.java
  src/test/java/seedu/duke/commands/ListCurrentBorrowingsCommandTest.java
  src/test/java/seedu/duke/commands/SearchCommandTest.java
  src/test/java/seedu/duke/data/ItemTest.java
  src/test/java/seedu/duke/parser/EditCommandParserTest.java
  src/test/java/seedu/duke/parser/SearchCommandParserTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  src/test/java/seedu/duke/stubs/BorrowRecordStubs.java
  src/test/java/seedu/duke/stubs/ItemListStubs.java
  src/test/java/seedu/duke/stubs/ItemStubs.java
  src/test/java/seedu/duke/stubs/ParserStubs.java
  test/data/load/invalidData.json
  test/data/load/validInputData.json
  test/data/save/actualData.json
  test/data/save/expectedData.json
Labels: type.Task, type.Bug, review.Ready

#189 Update Item in filtering records
  src/main/java/seedu/duke/commands/ListCurrentBorrowingsCommand.java
  src/main/java/seedu/duke/data/Item.java
  src/test/java/seedu/duke/data/ItemTest.java
  test/data/save/expectedData.json
Labels: type.Enhancement

#185 Update ListFutureBorrowingsCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/ListFutureBorrowingsCommand.java
Labels: type.Enhancement, priority.Medium, review.Ready

#192 Update InvMgr.java
  src/main/java/seedu/duke/InvMgr.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low, review.Ready

#197 Update List Borrowings Commands
  src/main/java/seedu/duke/commands/ListCurrentBorrowingsCommand.java
  src/main/java/seedu/duke/commands/ListFutureBorrowingsCommand.java
Labels: type.Bug, severity.Medium, review.Ready

#187 Modifies LostCommand to edit a lost item's quantity or delete it altogether
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/duke/commands/BorrowCommand.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/LostCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/Item.java
  src/main/java/seedu/duke/parser/LostCommandParser.java
  src/test/java/seedu/duke/commands/LostCommandTest.java
  src/test/java/seedu/duke/parser/LostCommandParserTest.java
  src/test/java/seedu/duke/stubs/ParserStubs.java
Labels: review.Ready

#199 Fix ListAvailableBorrowings, modifications to CancelFutureBorrowings
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/CancelFutureBorrowingsCommand.java
  src/main/java/seedu/duke/commands/ListAvailableBorrowingsCommand.java
  src/main/java/seedu/duke/parser/CancelFutureBorrowingsParser.java
  src/main/java/seedu/duke/parser/ListAvailableBorrowingsParser.java
  test/data/read/actualData.json
  test/data/save/expectedData.json
Labels: type.Bug, priority.Medium, review.Ready

#201 Update DeleteCommand
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/test/java/seedu/duke/commands/DeleteCommandTest.java
Labels: type.Task, priority.Medium, review.Ready

#202 Update HelpCommand with messages from other Commands
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/ListCurrentBorrowingsCommand.java
  src/main/java/seedu/duke/commands/ListFutureBorrowingsCommand.java
  src/main/java/seedu/duke/commands/ListOverdueBorrowingsCommand.java
Labels: type.Enhancement, review.Ready

#198 Update AddCommand.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/parser/AddCommandParserTest.java
Labels: type.Task, priority.High, review.Ready

#205 Refines LostCommand
  src/main/java/seedu/duke/commands/LostCommand.java
  src/main/java/seedu/duke/parser/LostCommandParser.java
  src/test/java/seedu/duke/commands/LostCommandTest.java
  src/test/java/seedu/duke/parser/LostCommandParserTest.java
  src/test/java/seedu/duke/stubs/ParserStubs.java
Labels: review.Ready

#210 Update DG with CancelFutureBorrowings and ListAvailableBorrowings
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CancelFutureBorrowingsRef.puml
  docs/diagrams/CancelFutureBorrowingsSequenceDiagram.puml
  docs/diagrams/ListAvailableBorrowingsSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/img/CancelFutureBorrowingsRef.png
  docs/img/CancelFutureBorrowingsSequenceDiagram.png
  docs/img/ListAvailableBorrowingsSequenceDiagram.png
  docs/img/ListCommandSequenceDiagram.png
  docs/team/cheshire-doge.md
  src/main/java/seedu/duke/commands/CancelFutureBorrowingsCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/parser/ListAvailableBorrowingsParser.java
Labels: type.Task, priority.Medium, review.Ready

#209 Fix for #203
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditCommand1SequenceDiagram.puml
  docs/img/EditCommand1SequenceDiagram.png
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/parser/CliSyntax.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/ParserUtils.java
  src/test/java/seedu/duke/commands/EditCommandTest.java
  src/test/java/seedu/duke/parser/EditCommandParserTest.java
  src/test/java/seedu/duke/parser/ParserUtilsTest.java
  src/test/java/seedu/duke/stubs/ParserStubs.java
Labels: review.Ready

#207 Update UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/common/Messages.java
Labels: type.Task, priority.High, review.Ready

#206 Update DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/BorrowCommandSequenceDiagram.puml
  docs/diagrams/CommandClassDiagram1.puml
  docs/diagrams/CommandClassDiagram2.puml
  docs/diagrams/CommandClassDiagram3.puml
  docs/diagrams/DescCommandSequenceDiagram.puml
  docs/diagrams/ItemListClassDiagram.puml
  docs/img/BorrowCommandSequenceDiagram.png
  docs/img/CommandClassDiagram.png
  docs/img/CommandClassDiagram1.png
  docs/img/CommandClassDiagram2.png
  docs/img/CommandClassDiagram3.png
  docs/img/DescCommandSequenceDiagram.png
  docs/img/ItemListClassDiagram.png
  src/main/java/seedu/duke/parser/BorrowCommandParser.java
Labels: type.Enhancement, review.Ready

#221 Update Jasper PPP (Final)
  docs/team/quitejasper.md
Labels: type.Task, priority.High, review.Ready

#213 Update DeveloperGuide.md for Jasper
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/diagrams/ListFutureBorrowings1SequenceDiagram.puml
  docs/diagrams/ListFutureBorrowings2SequenceDiagram.puml
  docs/diagrams/ListOverdueBorrowings1SequenceDiagram.puml
  docs/diagrams/ListOverdueBorrowings2SequenceDiagram.puml
  docs/img/AddCommandSequenceDiagram.png
  docs/img/DeleteCommandSequenceDiagram.png
  docs/img/ListFutureBorrowings1SequenceDiagram.png
  docs/img/ListFutureBorrowings2SequenceDiagram.png
  docs/img/ListOverdueBorrowings1SequenceDiagram.png
  docs/img/ListOverdueBorrowings2SequenceDiagram.png
  src/main/java/seedu/duke/commands/DeleteCommand.java
Labels: type.Task, priority.High, review.Ready

#180 Final PPP
  docs/team/IncompetentDev.md
  docs/team/incompetentdev.md
Labels: type.Task
